### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by AnatoliyOstapenko** [rootstrap/PagedLists#10]
Could you specify, where I have to add mentioned strings???:

```
Configuration

Set the number of elements per page you are expecting from your data source.

tableView.elementsPerPage = 20
The pagination delegate

tableView.updateDelegate = self
```

Could you write read file as to everybody has ability to read and understand what you mean?

**Comment by glm4** [comment]
@AnatoliyOstapenko which strings are you referring to?
I can update de documentation based on your feedback.

**Comment by AnatoliyOstapenko** [comment]
Where am I should put these codes:

tableView.elementsPerPage = 20

tableView.updateDelegate = self

How my view controller can see it?

Thanks in advance for your reply.

**Comment by AnatoliyOstapenko** [comment]
> @AnatoliyOstapenko which strings are you referring to?
> I can update de documentation based on your feedback.
Could you let me know
Where am I should put these codes as you mentioned in description file:

tableView.elementsPerPage = 20

tableView.updateDelegate = self

How my view controller can see it?

Thanks in advance for your reply.

**Comment by glm4** [comment]
@AnatoliyOstapenko you are correct, the view controller containing the table view or collection view can be the delegate and configure those parameters.
